[package]
name = "p2p"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
dryoc = "0.5.0"
log = "0.4.17"
rand = "0.8.5"
rsntp = "3.0.2"
sntpc = "0.3.4"
socket2 = "0.5.2"
