[package]
name = "udp-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
connection = {path = "../connection"}
rand = "0.8.5"
socket2 = "0.5.2"
